// website-svelte/src/components/GraphView.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import Sigma from 'sigma';
  import Graph from 'graphology';
  import type { GraphData } from '../types';
  import { selectedNodeId, selectedEdgeId, neighborIds, neighborEdgeIds, shortestPath, pathEdgeIds, metricSizes, metricColors, searchResults } from '../stores/graph';
  import { tick } from 'svelte';
  export let data: GraphData | null = null;
  let container: HTMLDivElement;
  let sigma: Sigma | null = null;

  const lightMode = typeof window !== 'undefined' && Boolean((window as any).__GRAPH_LIGHT_MODE__);

  // Local mirrors of store values for highlighting
  let _neighborIds = new Set<string>();
  let _neighborEdgeIds = new Set<string>();
  let _path = new Set<string>();
  let _pathEdges = new Set<string>();
  let _metricSizes = new Map<string, number>();
  let _metricColors = new Map<string, string>();
  let _searchIds = new Set<string>();
  let _selNode: string | null = null;
  let _selEdge: string | null = null;

  function applyHighlights(){
    if (!sigma || !data) return;
    const g = sigma.getGraph();
    g.forEachNode((n)=>{
      const base = g.getNodeAttribute(n,'color') as string;
      let color = _metricColors.get(n) ?? base;
      let size = _metricSizes.get(n) ?? (g.getNodeAttribute(n,'size') as number);
      if (_searchIds.size>0) color = _searchIds.has(n) ? '#60a5fa' : '#cbd5f5';
      if (_neighborIds.has(n)) { color = '#34d399'; size = size + 0.9; }
      if (_path.has(n)) { color = '#facc15'; size = size + 1.1; }
      if (_selNode && n===_selNode) { color = '#f97316'; size = size + 1.3; }
      g.setNodeAttribute(n,'color',color); g.setNodeAttribute(n,'size',size);
    });
    g.forEachEdge((e)=>{
      const base = g.getEdgeAttribute(e,'color') as string; let color = base; let size = (g.getEdgeAttribute(e,'size') as number) ?? 1;
      if (_neighborEdgeIds.has(e)) { color='#34d399'; size = Math.max(size, 1.75); }
      if (_pathEdges.has(e)) { color='#facc15'; size = Math.max(size, 2); }
      if (_selEdge && e===_selEdge) { color='#f97316'; size = Math.max(size, 2.25); }
      g.setEdgeAttribute(e,'color',color); g.setEdgeAttribute(e,'size',size);
    });
  }

  onMount(() => {
    if (lightMode) return;
    if (!data) return;
    const g = new Graph({ type: 'undirected', allowSelfLoops: true });
    data.nodes.forEach((n) => {
      g.addNode(n.id, {
        label: (n.properties?.name as string) ?? n.id,
        x: n.x ?? Math.random() * 10,
        y: n.y ?? Math.random() * 10,
        size: n.size,
        color: '#334155',
        raw: n,
      });
    });
    data.edges.forEach((e) => {
      if (g.hasNode(e.source) && g.hasNode(e.target))
        g.addEdgeWithKey(e.id, e.source, e.target, {
          label: e.type,
          color: '#94a3b8',
          raw: e,
        });
    });
    sigma = new Sigma(g, container, { renderLabels: true });
    sigma.on('clickNode', (e) => { selectedNodeId.set(e.node as string); selectedEdgeId.set(null); });
    sigma.on('clickEdge', (e) => { selectedEdgeId.set(e.edge as string); });

    // Subscribe to store changes and re-apply highlights
    const unsubs = [
      neighborIds.subscribe(v=>{ _neighborIds = new Set(v); applyHighlights(); }),
      neighborEdgeIds.subscribe(v=>{ _neighborEdgeIds = new Set(v); applyHighlights(); }),
      shortestPath.subscribe(v=>{ _path = new Set(v); applyHighlights(); }),
      pathEdgeIds.subscribe(v=>{ _pathEdges = new Set(v); applyHighlights(); }),
      metricSizes.subscribe(v=>{ _metricSizes = new Map(v); applyHighlights(); }),
      metricColors.subscribe(v=>{ _metricColors = new Map(v); applyHighlights(); }),
      searchResults.subscribe(v=>{ _searchIds = new Set((v||[]).map((n:any)=>n.id)); applyHighlights(); }),
      selectedNodeId.subscribe(v=>{ _selNode = v; applyHighlights(); }),
      selectedEdgeId.subscribe(v=>{ _selEdge = v; applyHighlights(); }),
    ];
    // Initial paint after mount
    tick().then(applyHighlights);
    // Clean up subscriptions on destroy
    onDestroy(()=>{ unsubs.forEach(u=>u()); });
  });
  onDestroy(() => { sigma?.kill(); sigma = null; });
</script>

{#if lightMode}
  <div data-testid="graph-light-mode" style="width:100%;height:600px;border-radius:12px;border:1px solid #e2e8f0;display:grid;place-items:center;background:#f8fafc;color:#64748b;text-align:center">
    <div>
      <p>Graph rendering disabled for CI run.</p>
      <p class="muted small">Interactive canvas loads in standard builds.</p>
    </div>
  </div>
{:else}
  <div bind:this={container} style="width:100%;height:600px;border-radius:12px;border:1px solid #e2e8f0"></div>
{/if}

// website/src/GraphView.tsx
import { useEffect, useRef } from "react";
import Graph from "graphology";
import Sigma from "sigma";
import type { GraphEdge, GraphNode } from "./types";

const labelColors: Record<string, string> = {
  Character: "#2563eb",
  Ability: "#7c3aed",
  Mechanic: "#059669",
  Archetype: "#f97316",
};

interface GraphViewProps {
  nodes: GraphNode[];
  edges: GraphEdge[];
  highlightIds: Set<string>;
  neighborIds?: Set<string>;
  neighborEdgeIds?: Set<string>;
  pathNodeIds?: Set<string>;
  pathEdgeIds?: Set<string>;
  selectedNodeId?: string | null;
  pathStartId?: string | null;
  pathEndId?: string | null;
  selectedEdgeId?: string | null;
  onNodeSelect?: (node: GraphNode | null) => void;
  onEdgeSelect?: (edge: GraphEdge | null) => void;
  metricSizes?: Map<string, number>;
  metricColors?: Map<string, string>;
}

export function GraphView({
  nodes,
  edges,
  highlightIds,
  neighborIds,
  neighborEdgeIds,
  pathNodeIds,
  pathEdgeIds,
  selectedNodeId,
  pathStartId,
  pathEndId,
  selectedEdgeId,
  onNodeSelect,
  onEdgeSelect,
  metricSizes,
  metricColors,
}: GraphViewProps) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const sigmaRef = useRef<Sigma | null>(null);
  const lightMode = typeof window !== "undefined" && Boolean((window as any).__GRAPH_LIGHT_MODE__);

  useEffect(() => {
    if (lightMode) {
      sigmaRef.current?.kill();
      sigmaRef.current = null;
      return;
    }

    const g = new Graph({ type: "undirected", allowSelfLoops: true, multi: true });

    nodes.forEach((node) => {
      const color = labelColors[node.label] ?? "#334155";
      const baseSize = typeof node.size === "number" ? node.size : 1.5;
      g.addNode(node.id, {
        label: (node.properties?.name as string | undefined) ?? node.id,
        color,
        baseColor: color,
        size: baseSize,
        baseSize,
        x: node.x ?? Math.random() * 10,
        y: node.y ?? Math.random() * 10,
        raw: node,
      });
    });

    edges.forEach((edge) => {
      if (!g.hasNode(edge.source) || !g.hasNode(edge.target)) {
        return;
      }
      if (g.hasEdge(edge.id)) {
        return;
      }
      const baseColor = edge.type === "STRONG_AGAINST" ? "#dc2626" : edge.type === "WEAK_AGAINST" ? "#2563eb" : "#94a3b8";
      const baseSize = edge.type === "STRONG_AGAINST" ? 2 : 1;
      g.addEdgeWithKey(edge.id, edge.source, edge.target, {
        label: edge.type,
        color: baseColor,
        baseColor,
        size: baseSize,
        baseSize,
        raw: edge,
      });
    });

    if (containerRef.current) {
      sigmaRef.current?.kill();
      const renderer = new Sigma(g, containerRef.current, {
        renderLabels: true,
      });
      sigmaRef.current = renderer;

      const handleClickNode = (event: { node: string }) => {
        const attributes = g.getNodeAttributes(event.node);
        const raw = attributes.raw as GraphNode | undefined;
        onNodeSelect?.(raw ?? null);
        onEdgeSelect?.(null);
      };

      const handleClickEdge = (event: { edge: string }) => {
        const attributes = g.getEdgeAttributes(event.edge);
        const raw = attributes.raw as GraphEdge | undefined;
        onEdgeSelect?.(raw ?? null);
      };

      const handleClickStage = () => {
        onNodeSelect?.(null);
        onEdgeSelect?.(null);
      };

      renderer.on("clickNode", handleClickNode);
      renderer.on("clickEdge", handleClickEdge);
      renderer.on("clickStage", handleClickStage);

      return () => {
        renderer.removeListener("clickNode", handleClickNode);
        renderer.removeListener("clickEdge", handleClickEdge);
        renderer.removeListener("clickStage", handleClickStage);
        renderer.kill();
      };
    }
  }, [nodes, edges, onNodeSelect, onEdgeSelect, lightMode]);

  useEffect(() => {
    if (lightMode) {
      return;
    }

    const renderer = sigmaRef.current;
    if (!renderer) return;

    const graph = renderer.getGraph();
    const neighborSet = neighborIds ?? new Set<string>();
    const pathNodeSet = pathNodeIds ?? new Set<string>();
    const pathEdgeSet = pathEdgeIds ?? new Set<string>();
    const neighborEdgeSet = neighborEdgeIds ?? new Set<string>();
    const highlightActive = highlightIds.size > 0;
    const metricSizeMap = metricSizes ?? new Map<string, number>();
    const metricColorMap = metricColors ?? new Map<string, string>();

    graph.forEachNode((nodeKey) => {
      const baseColor = graph.getNodeAttribute(nodeKey, "baseColor") as string;
      const baseSize = (graph.getNodeAttribute(nodeKey, "baseSize") as number) ?? 1.5;
      let color = metricColorMap.get(nodeKey) ?? baseColor;
      let size = metricSizeMap.get(nodeKey) ?? baseSize;

      if (highlightActive) {
        color = highlightIds.has(nodeKey) ? "#60a5fa" : "#cbd5f5";
      }

      if (neighborSet.has(nodeKey)) {
        color = "#34d399";
        size = baseSize + 0.9;
      }

      if (pathNodeSet.has(nodeKey)) {
        color = "#facc15";
        size = baseSize + 1.1;
      }

      if (selectedNodeId && nodeKey === selectedNodeId) {
        color = "#f97316";
        size = baseSize + 1.3;
      }

      if (pathStartId && nodeKey === pathStartId) {
        color = "#38bdf8";
        size = baseSize + 1.5;
      }

      if (pathEndId && nodeKey === pathEndId) {
        color = "#ef4444";
        size = baseSize + 1.5;
      }

      graph.setNodeAttribute(nodeKey, "color", color);
      graph.setNodeAttribute(nodeKey, "size", size);
    });

    graph.forEachEdge((edgeKey) => {
      const baseColor = graph.getEdgeAttribute(edgeKey, "baseColor") as string;
      const baseSize = (graph.getEdgeAttribute(edgeKey, "baseSize") as number) ?? 1;
      const attributes = graph.getEdgeAttributes(edgeKey);
      const raw = attributes.raw as GraphEdge;
      let color = baseColor;
      let size = baseSize;

      if (highlightActive) {
        const sourceHighlighted = highlightIds.has(raw.source);
        const targetHighlighted = highlightIds.has(raw.target);
        color = sourceHighlighted && targetHighlighted ? baseColor : "#e2e8f0";
      }

      if (neighborEdgeSet.has(raw.id)) {
        color = "#34d399";
        size = Math.max(size, baseSize + 0.75);
      }

      if (pathEdgeSet.has(raw.id)) {
        color = "#facc15";
        size = Math.max(size, baseSize + 1);
      }

      if (selectedEdgeId && raw.id === selectedEdgeId) {
        color = "#f97316";
        size = Math.max(size, baseSize + 1.25);
      }

      graph.setEdgeAttribute(edgeKey, "color", color);
      graph.setEdgeAttribute(edgeKey, "size", size);
    });
  }, [
    highlightIds,
    neighborIds,
    neighborEdgeIds,
    pathNodeIds,
    pathEdgeIds,
    selectedNodeId,
    pathStartId,
    pathEndId,
    selectedEdgeId,
    metricSizes,
    metricColors,
    lightMode,
  ]);

  if (lightMode) {
    return (
      <div
        style={{
          width: "100%",
          height: "600px",
          borderRadius: "0.75rem",
          border: "1px solid #e2e8f0",
          display: "grid",
          placeItems: "center",
          backgroundColor: "#f8fafc",
          color: "#64748b",
          textAlign: "center",
          padding: "1rem",
        }}
        data-testid="graph-light-mode"
      >
        <div>
          <p>Graph rendering disabled for CI run.</p>
          <p className="muted small">Interactive canvas loads in standard builds.</p>
        </div>
      </div>
    );
  }

  return <div ref={containerRef} style={{ width: "100%", height: "600px", borderRadius: "0.75rem", border: "1px solid #e2e8f0" }} />;
}
